name = hollowengine-loom
description = A Gradle plugin for HollowEngine modding on Fabric, Forge and Quilt.
url = https://github.com/hollowhorizon/hollowengine-loom

kotlin.stdlib.default.dependency = false
# Suppress a deprecation warning within the Kotlin Gradle plugin
kotlin.mpp.keepMppDependenciesIntactInPoms = true
